namespace: slim_os
name: windows
version: 1.0.0

readme: README.md

authors:
  - ChunPanYung@gmail.com

description: your collection description

license:
  - MIT

license_file: ''

tags:
  - windows

dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker

build_ignore: []
