---
namespace: ansi_colle
name: slim_os
version: 1.0.0
readme: README.md
authors:
  - Chun Pan Yung <31672021+ChunPanYung@users.noreply.github.com>

description: |
  Collection of os build after freshly install OS.
  It will add or remove packages.
repository: https://github.com/ChunPanYung/ansi_colle.slim_os
license:
  - MIT

tags:
  - linux
  - windows
