# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  changelog:*:
    desc: |
      Create or append to CHANGELOG.md, need tag version.
      TAG -> Create a git tag, ex: v1.0.1.
    vars:
      TAG: "{{index .MATCH 0}}"
    cmds:
      - "git-cliff --prepend CHANGELOG.md --unreleased --tag {{.TAG}}"

  playbook:
    desc: |
      Run this plabyook:
      INVENTORY -> inventory file path, default is localhost.
    vars:
      INVENTORY: '{{.INVENTORY | default "127.0.0.1, --connection=local"}}'
    cmds:
      - cmd: >-
          ansible-playbook ansi_colle.slim_os.site --ask-become-pass
          --inventory {{.INVENTORY}}
  install:
    desc: |
      Install this collection and requirement.
      BRANCH -> Specify git branch or tag, default is main.
    vars:
      BRANCH: '{{.BRANCH | default "main"}}'
    cmds:
      - "ansible-galaxy collection install --upgrade community.general"
      - "ansible-playbook ./playbooks/install.yml --extra-vars git_branch={{.BRANCH}}"
