---
galaxy_info:
  author: Chun Pan Yung
  description: Configure all virtual machines with common settings.

  license: GPL-3.0

  min_ansible_version: "2.14"

  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
