---
namespace: slim_os
name: dnf
version: 1.0.0
readme: README.md
authors:
  - Chun Pan Yung <31672021+ChunPanYung@users.noreply.github.com>

description: |
  Collection of os build after freshly install OS.
  It will add or remove packages.
license:
  - GPL-2.0-or-later

tags:
  - linux
