---
# tasks file for ubuntu
- name: Pre_tasks for role
  become: true
  block:
    - name: Update repo cache (debian based OS)
      ansible.builtin.apt:
        update_cache: true
      changed_when: false  # not considered change when cache is updated

    - name: Remove abomination
      ansible.builtin.apt:
        name: snapd
        state: absent
        purge: true

    - name: Remove packages
      ansible.builtin.apt:
        name: thunderbird
        state: absent
        purge: true

    - name: Install nala package manager
      ansible.builtin.apt:
        name: nala

    - name: Update packages and remove unused ones
      ansible.builtin.apt:
        autoremove: true

- name: Customize $HOME/.bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/bashrc.sh"
    block: "{{ lookup('ansible.builtin.file', 'bashrc.sh') }}"
