---
namespace: slim_linux
name: apt

version: 1.0.0
readme: README.md

authors:
  - Chun Pan Yung

repository: http://github.com/ChunPanYung/slim_linux
description: Remove excessive packages from Linux Distro.

license:
  - GPL-2.0-or-later

tags:
  - linux
