---
namespace: slim_os
name: apt
version: 1.0.0
readme: README.md
authors:
  - Chun Pan Yung

description: Remove excessive packages from apt-based Linux OS.

license:
  - MIT

tags:
  - linux
  - infrastructure

dependencies:
  "community.general": "*"

repository: http://github.com/ChunPanYung/slim_os
build_ignore: []
