---
galaxy_info:
  author: Chun Pan Yung
  description: Remove excessive debian packages.

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - system

dependencies: []
