---
- name: Remove bloatware from linux
  hosts: all
  vars_prompt:
    - name: ansible_become_pass
      prompt: "BECOME password"

  roles:
    - role: ansi_colle.slim_os.fedora
      when: ansible_facts['distribution'] == "Fedora"
    - role: ansi_colle.slim_os.ubuntu
      when: ansible_facts['distribution'] == "Ubuntu"
