---
# tasks file for fedora
- name: Execute following block using sudo privilege
  become: true
  block:
    - name: Remove default packages on Gnome Desktop
      ansible.builtin.dnf:
        name:
          - cheese
          - gnome-boxes
          - gnome-contacts
          - gnome-connections
          - gnome-maps
          - mediawriter
        state: absent
      when: ansible_env.XDG_CURRENT_DESKTOP == 'GNOME'

    - name: Remove default packages on KDE Desktop
      ansible.builtin.dnf:
        name:
          - akonadi-import-wizard
          - akregator
          - dnfdragora
          - dragon
          - kaddressbook
          - kamoso
          - kdepim
          - kgpg
          - kmahjongg
          - kmail
          - kmines
          - kolourpaint
          - kmouth
          - kontact
          - konversation
          - korganizer
          - kpat
          - krdc
          - krfb
          - qt5-qdbusviewer
        state: absent
      when: ansible_env.XDG_CURRENT_DESKTOP == 'KDE'

    - name: Remove packages from KDE
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - '@libreoffice'
        - 'libreoffice-core'

    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: true

    - name: Optimize dnf configuration
      community.general.ini_file:
        mode: '0644'
        path: /etc/dnf/dnf.conf
        section: main
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        backup: true
      loop:
        - {key: 'max_parallel_downloads', value: '5'}
        - {key: 'fastestmirror', value: 'True'}
        - {key: 'keepcache', value: 'True'}

- name: Enable RPM fusion
  become: true
  block:
    - name: Install RPM Fusion gpg keys for free and nonfree
      vars:
        rpm_link: https://rpmfusion.org/keys?action=AttachFile&do=get&target=
      ansible.builtin.rpm_key:
        key: "{{ item.key }}"
        fingerprint: "{{ item.fingerprint }}"
      loop:
        - {key: "{{ rpm_link }}RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020",
           fingerprint: "79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65"}
        - {key: "{{ rpm_link }}RPM-GPG-KEY-rpmfusion-free-fedora-2020",
           fingerprint: "E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E"}

    - name: Enable RPM fusion, free and nonfree repository
      ansible.builtin.dnf:
        name: "{{ item }}"
      vars:
        rpm_link: https://mirrors.rpmfusion.org
        free_rpm: "rpmfusion-free-release-{{ ansible_distribution_version }}"
        nonfree_rpm: >-
          rpmfusion-nonfree-release-{{ ansible_distribution_version }}
      loop:
        - "{{ rpm_link }}/free/fedora/{{ free_rpm }}.noarch.rpm"
        - "{{ rpm_link }}/nonfree/fedora/{{ nonfree_rpm }}.noarch.rpm"

- name: Setup bash
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: "{{ lookup('ansible.builtin.file', 'bashrc.sh') }}"
    marker: "# {mark} CUSTOMIZE BASH"
